"use client";

import { useEffect, useState } from "react";
import { Download, Edit3, Eye, Filter, Plus, Trash2 } from "lucide-react";
import { api, download } from "../lib/api";
import { money } from "../lib/format";
import type { AuditoriaResponse, CategoriaCatalogoResponse, ClienteResponse, ItemCatalogoResponse, MarcaMotoResponse, MotovehiculoResponse, PageResponse } from "../lib/types";
import { ConfirmModal, Dialog, EmptyState, Pagination, SearchBox } from "./ui";
import { AbmFormModal, type AbmField, VehicleAbmModal } from "./modal/abm-form-modal";

type Resource = "clients" | "vehicles" | "catalog" | "audit";
type DataRow = Record<string, string | number | boolean | undefined>;
const requestError = (reason: unknown) => reason instanceof Error ? reason.message : "No fue posible completar la operación.";
const iso = (value: string) => new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));

const configs = {
  clients: { title: "Clientes", singular: "cliente", description: "Fichas de contacto, vehículos asociados e historial comercial.", endpoint: "/clientes", exportPath: "/clientes/export.xlsx", columns: ["Nombre", "Documento", "Teléfono", "Motos", "Pedidos", "Estado"], fields: [{ key: "nombre", label: "Nombre y apellido / razón social", required: true }, { key: "documento", label: "DNI o CUIT" }, { key: "telefono", label: "Teléfono", type: "tel", required: true }, { key: "email", label: "Email", type: "email" }, { key: "direccion", label: "Dirección" }, { key: "observaciones", label: "Observaciones", type: "textarea", wide: true }] },
  vehicles: { title: "Motos", singular: "motovehículo", description: "Un vehículo conserva su vínculo con el cliente y todo su historial.", endpoint: "/motovehiculos", exportPath: "/motovehiculos/export.xlsx", columns: ["Marca y modelo", "Patente", "Cliente", "Año", "KM", "Estado"], fields: [] },
  catalog: { title: "Catálogo", singular: "ítem", description: "Piezas y trabajos con precios base y trazabilidad de actualizaciones.", endpoint: "/catalogo-items", exportPath: "/catalogo-items/export.xlsx", columns: ["Tipo", "Descripción", "Categoría", "Precio", "Estado"], fields: [{ key: "tipo", label: "Tipo", type: "select", required: true, options: [{ value: "Pieza", label: "Pieza" }, { value: "Trabajo", label: "Trabajo" }] }, { key: "descripcion", label: "Descripción estandarizada", required: true }, { key: "categoriaId", label: "Categoría", type: "select", required: true }, { key: "precioBase", label: "Precio base", type: "number", required: true }, { key: "observaciones", label: "Observaciones", type: "textarea", wide: true }] },
} as const;

function rowFor(resource: Exclude<Resource, "audit">, item: ClienteResponse | MotovehiculoResponse | ItemCatalogoResponse): DataRow {
  if (resource === "clients") { const client = item as ClienteResponse; return { ...client, estado: client.activo ? "Activo" : "Inactivo" }; }
  if (resource === "vehicles") { const vehicle = item as MotovehiculoResponse; return { ...vehicle, estado: vehicle.activo ? "Activo" : "Inactivo" }; }
  const catalog = item as ItemCatalogoResponse; return { ...catalog, estado: catalog.activo ? "Activo" : "Inactivo" };
}
function cell(row: DataRow, column: string) {
  if (column === "Nombre") return row.nombre;
  if (column === "Marca y modelo") return `${row.marca} ${row.modelo}`;
  if (column === "Documento") return row.documento || "—";
  if (column === "Teléfono") return row.telefono;
  if (column === "Motos") return row.motos;
  if (column === "Pedidos") return row.pedidos;
  if (column === "Año") return row.anio || "—";
  if (column === "KM") return row.kilometraje || "—";
  if (column === "Tipo") return row.tipo;
  if (column === "Descripción") return row.descripcion;
  if (column === "Categoría") return row.categoria || "—";
  if (column === "Precio") return money(Number(row.precioBase));
  if (column === "Estado") return <span className={`record-state ${row.estado === "Activo" ? "active" : "inactive"}`}>{String(row.estado)}</span>;
  return "—";
}

export function AdminView({ resource, notify }: { resource: Resource; notify: (message: string) => void }) {
  if (resource === "audit") return <AuditView />;
  return <Records resource={resource} notify={notify} />;
}

function Records({ resource, notify }: { resource: Exclude<Resource, "audit">; notify: (message: string) => void }) {
  const config = configs[resource]; const [rows, setRows] = useState<DataRow[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Todos"); const [page, setPage] = useState(1); const [total, setTotal] = useState(1); const [editing, setEditing] = useState<DataRow | null>(null); const [detail, setDetail] = useState<DataRow | null>(null); const [deleting, setDeleting] = useState<DataRow | null>(null); const [clients, setClients] = useState<ClienteResponse[]>([]); const [brands, setBrands] = useState<MarcaMotoResponse[]>([]); const [categories, setCategories] = useState<CategoriaCatalogoResponse[]>([]); const [error, setError] = useState<string | null>(null);
  const load = () => { const params = { q: query || undefined, activo: filter === "Todos" ? undefined : filter === "Activo", page: page - 1, size: 20 }; void api<PageResponse<ClienteResponse | MotovehiculoResponse | ItemCatalogoResponse>>(config.endpoint, {}, params).then((result) => { setRows(result.content.map((item) => rowFor(resource, item))); setTotal(result.totalPages || 1); }).catch((reason) => setError(requestError(reason))); };
  useEffect(load, [resource, query, filter, page, config.endpoint]);
  useEffect(() => { if (resource === "vehicles") void Promise.all([api<PageResponse<ClienteResponse>>("/clientes", {}, { size: 100, activo: true }), api<MarcaMotoResponse[]>("/configuracion/marcas-moto")]).then(([clientPage, nextBrands]) => { setClients(clientPage.content); setBrands(nextBrands.filter((brand) => brand.activo)); }).catch((reason) => setError(requestError(reason))); if (resource === "catalog") void api<CategoriaCatalogoResponse[]>("/configuracion/categorias-catalogo").then((nextCategories) => setCategories(nextCategories.filter((category) => category.activo))).catch((reason) => setError(requestError(reason))); }, [resource]);
  const fields: AbmField[] = resource === "catalog" ? configs.catalog.fields.map((field) => field.key === "categoriaId" ? { ...field, options: categories.map((category) => ({ value: category.id, label: category.nombre })) } : field) : resource === "clients" ? [...configs.clients.fields] : [];
  const submit = async (values: Record<string, string>) => { try { const payload = resource === "vehicles" ? { ...values, anio: values.anio ? Number(values.anio) : null, kilometraje: values.kilometraje ? Number(values.kilometraje) : null } : resource === "catalog" ? { ...values, precioBase: Number(values.precioBase) } : values; await api(`${config.endpoint}${editing?.id ? `/${editing.id}` : ""}`, { method: editing?.id ? "PUT" : "POST", body: JSON.stringify(payload) }); setEditing(null); load(); notify(`${config.singular[0].toUpperCase()}${config.singular.slice(1)} guardado.`); } catch (reason) { setError(requestError(reason)); } };
  const params = { q: query || undefined, activo: filter === "Todos" ? undefined : filter === "Activo" };
  return <div className="page"><div className="page-heading"><div><h1>{config.title}</h1><p>{config.description}</p></div><button className="button primary" onClick={() => setEditing({})}><Plus size={19} />Nuevo {config.singular}</button></div>{error && <p className="login-pending" role="alert">{error}</p>}<section className="panel table-panel"><div className="filter-bar"><SearchBox value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder={`Buscar ${config.singular}`} /><label><Filter size={16} /><select value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1); }}><option>Todos</option><option>Activo</option><option>Inactivo</option></select></label><button className="button secondary" onClick={() => void download(config.exportPath, `${config.title.toLowerCase()}.xlsx`, params)}><Download size={17} />Exportar Excel</button></div>{rows.length ? <table><thead><tr>{config.columns.map((column) => <th key={column}>{column}</th>)}<th>Acciones</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}>{config.columns.map((column) => <td key={column}>{cell(row, column)}</td>)}<td className="table-actions"><button onClick={() => setDetail(row)} aria-label={`Ver ${config.singular}`}><Eye size={17} /></button><button onClick={() => setEditing(row)} aria-label={`Editar ${config.singular}`}><Edit3 size={17} /></button><button className="danger-action" onClick={() => setDeleting(row)} aria-label={`Eliminar ${config.singular}`}><Trash2 size={17} /></button></td></tr>)}</tbody></table> : <EmptyState title={`No hay ${config.title.toLowerCase()} para mostrar`} body="Probá ajustar los filtros o crear un registro." action={<button className="button primary" onClick={() => setEditing({})}>Crear registro</button>} />}<Pagination page={page} total={total} onPage={setPage} /></section>{resource === "vehicles" ? <VehicleAbmModal key={String(editing?.id ?? "new")} open={editing !== null} mode={editing?.id ? "modificar" : "agregar"} initialValues={editing ?? {}} brands={brands} clients={clients} onClose={() => setEditing(null)} onSubmit={submit} /> : <AbmFormModal key={String(editing?.id ?? "new")} open={editing !== null} resource={config.singular} mode={editing?.id ? "modificar" : "agregar"} fields={fields} initialValues={editing ?? {}} onClose={() => setEditing(null)} onSubmit={submit} />}<RecordDetail open={detail !== null} title={config.singular} record={detail} onClose={() => setDetail(null)} onEdit={() => { setEditing(detail); setDetail(null); }} /><ConfirmModal open={deleting !== null} title={`Eliminar ${config.singular}`} body={`El registro seleccionado pasará a inactivo.`} confirmLabel="Sí, eliminar" onClose={() => setDeleting(null)} onConfirm={() => { if (!deleting) return; void api(`${config.endpoint}/${deleting.id}`, { method: "DELETE" }).then(() => { setDeleting(null); load(); notify("Registro eliminado."); }).catch((reason) => setError(requestError(reason))); }} /></div>;
}

function RecordDetail({ open, title, record, onClose, onEdit }: { open: boolean; title: string; record: DataRow | null; onClose: () => void; onEdit: () => void }) { return <Dialog open={open} title={`Ficha de ${title}`} onClose={onClose}><dl className="record-detail">{Object.entries(record ?? {}).filter(([key]) => !["id", "activo", "estado", "createdAt", "updatedAt"].includes(key)).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value ?? "—")}</dd></div>)}</dl><div className="modal-actions"><button className="button secondary" onClick={onClose}>Cerrar</button><button className="button primary" onClick={onEdit}>Editar</button></div></Dialog>; }

function AuditView() { const [query, setQuery] = useState(""); const [module, setModule] = useState("Todos"); const [rows, setRows] = useState<AuditoriaResponse[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { void api<AuditoriaResponse[]>("/auditoria", {}, { q: query || undefined, modulo: module === "Todos" ? undefined : module }).then(setRows).catch((reason) => setError(requestError(reason))); }, [query, module]); return <div className="page"><div className="page-heading"><div><h1>Auditoría</h1><p>Altas, ediciones y transiciones de estado registradas.</p></div></div>{error && <p className="login-pending" role="alert">{error}</p>}<section className="panel table-panel"><div className="filter-bar"><SearchBox value={query} onChange={setQuery} placeholder="Usuario, módulo o descripción" /><label><Filter size={16} /><select value={module} onChange={(event) => setModule(event.target.value)}><option>Todos</option><option>Pedidos</option><option>Catálogo</option><option>Clientes</option><option>Motovehículos</option></select></label></div>{rows.length ? <table><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Módulo</th><th>Acción</th><th>Descripción</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{iso(row.fecha)}</td><td>{row.usuario}</td><td>{row.modulo}</td><td>{row.accion}</td><td>{row.descripcion}</td></tr>)}</tbody></table> : <EmptyState title="No hay registros de auditoría" body="No se encontraron eventos con esos filtros." />}</section></div>; }

type Setting = { title: string; description: string; endpoint: string; fields: AbmField[]; name: (item: DataRow) => string };
const settings: Setting[] = [{ title: "Marcas de motos", description: "Opciones disponibles en el alta y edición de motos.", endpoint: "/configuracion/marcas-moto", fields: [{ key: "nombre", label: "Marca", required: true, wide: true }], name: (item) => String(item.nombre) }, { title: "Categorías de catálogo", description: "Clasificación disponible para piezas y trabajos.", endpoint: "/configuracion/categorias-catalogo", fields: [{ key: "nombre", label: "Categoría", required: true, wide: true }], name: (item) => String(item.nombre) }, { title: "Usuarios del sistema", description: "Usuarios y perfiles de acceso del taller.", endpoint: "/configuracion/usuarios", fields: [{ key: "username", label: "Usuario", required: true }, { key: "nombre", label: "Nombre", required: true }, { key: "email", label: "Email", type: "email" }, { key: "rol", label: "Perfil", type: "select", required: true, options: [{ value: "ADMINISTRACION", label: "Administración" }, { value: "OPERARIO", label: "Operario" }] }, { key: "password", label: "Contraseña", type: "text" }], name: (item) => `${item.nombre} · ${item.rol === "ADMINISTRACION" ? "Administración" : "Operario"}` }];

export function SettingsView({ notify }: { notify: (message: string) => void }) { return <div className="page"><div className="page-heading"><div><h1>Administración</h1><p>Marcas, categorías y usuarios del sistema.</p></div></div><section className="settings-grid">{settings.map((setting) => <ConfigSection key={setting.endpoint} setting={setting} notify={notify} />)}</section></div>; }
function ConfigSection({ setting, notify }: { setting: Setting; notify: (message: string) => void }) { const [entries, setEntries] = useState<DataRow[]>([]); const [editing, setEditing] = useState<DataRow | null>(null); const [deleting, setDeleting] = useState<DataRow | null>(null); const [error, setError] = useState<string | null>(null); const load = () => { void api<DataRow[]>(setting.endpoint).then(setEntries).catch((reason) => setError(requestError(reason))); }; useEffect(load, [setting.endpoint]); const submit = async (values: Record<string, string>) => { try { const payload = { ...values, ...(editing?.id && !values.password ? { password: null } : {}) }; await api(`${setting.endpoint}${editing?.id ? `/${editing.id}` : ""}`, { method: editing?.id ? "PUT" : "POST", body: JSON.stringify(payload) }); setEditing(null); load(); notify("Configuración guardada."); } catch (reason) { setError(requestError(reason)); } }; return <section className="panel config-section"><div className="config-head"><div><h2>{setting.title}</h2><p>{setting.description}</p></div><button className="button secondary" onClick={() => setEditing({})}><Plus size={16} />Agregar</button></div>{error && <p className="login-pending" role="alert">{error}</p>}<ul className="config-list">{entries.map((entry) => <li key={String(entry.id)}><span>{setting.name(entry)}</span><div className="table-actions"><button onClick={() => setEditing(entry)} aria-label={`Editar ${setting.name(entry)}`}><Edit3 size={16} /></button><button className="danger-action" onClick={() => setDeleting(entry)} aria-label={`Eliminar ${setting.name(entry)}`}><Trash2 size={16} /></button></div></li>)}</ul><AbmFormModal key={String(editing?.id ?? "new")} open={editing !== null} resource={setting.title.slice(0, -1).toLowerCase()} mode={editing?.id ? "modificar" : "agregar"} initialValues={editing ?? {}} fields={setting.fields} onClose={() => setEditing(null)} onSubmit={submit} /><ConfirmModal open={deleting !== null} title="Eliminar configuración" body={`¿Querés eliminar “${deleting ? setting.name(deleting) : ""}”?`} confirmLabel="Sí, eliminar" onClose={() => setDeleting(null)} onConfirm={() => { if (!deleting) return; void api(`${setting.endpoint}/${deleting.id}`, { method: "DELETE" }).then(() => { setDeleting(null); load(); notify("Configuración eliminada."); }).catch((reason) => setError(requestError(reason))); }} /></section>; }
