"use client";
import type { ReactNode } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Search, X } from "lucide-react";
import type { OrderStatus } from "../lib/types";

export function StatusBadge({status}:{status:OrderStatus}) { const map={"En proceso":Clock3,"Aprobado":CheckCircle2,"Pagado":CheckCircle2,"Cancelado":AlertTriangle}; const Icon=map[status]; return <span className={`status status-${status.toLowerCase().replace(" ","-")}`}><Icon size={14}/>{status}</span>; }
export function SearchBox({value,onChange,placeholder="Buscar..."}:{value:string;onChange:(value:string)=>void;placeholder?:string}) { return <label className="search"><Search size={18}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button aria-label="Limpiar búsqueda" onClick={()=>onChange("")}><X size={16}/></button>}</label>; }
export function ConfirmModal({open,title,body,confirmLabel,variant="danger",onConfirm,onClose}:{open:boolean;title:string;body:string;confirmLabel:string;variant?:"danger"|"success";onConfirm:()=>void;onClose:()=>void}) { if(!open)return null; return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">{title}</h2><p>{body}</p><div className="modal-actions"><button className="button secondary" onClick={onClose}>Cancelar</button><button className={`button ${variant}`} onClick={onConfirm}>{confirmLabel}</button></div></section></div>; }
export function EmptyState({title,body,action}:{title:string;body:string;action?:ReactNode}) { return <div className="empty"><div className="empty-mark">—</div><h3>{title}</h3><p>{body}</p>{action}</div>; }
export function Pagination({page,total,onPage}:{page:number;total:number;onPage:(page:number)=>void}) { return <div className="pagination"><span>Página {page} de {total}</span><div><button disabled={page===1} onClick={()=>onPage(page-1)}>Anterior</button><button disabled={page===total} onClick={()=>onPage(page+1)}>Siguiente</button></div></div>; }
