"use client";

import { useEffect, useState } from "react";
import { Download, Edit3, FileDown, Filter, Plus, Trash2 } from "lucide-react";
import { api, download } from "../lib/api";
import { money } from "../lib/format";
import type { ClienteResponse, OrderStatus, PageResponse, PedidoResponse, ReporteResponse } from "../lib/types";
import { EmptyState, Pagination, SearchBox, StatusBadge } from "./ui";

const date = (value: string) => new Intl.DateTimeFormat("es-AR").format(new Date(value));
const errorMessage = (reason: unknown) => reason instanceof Error ? reason.message : "No fue posible cargar la información.";

export function Dashboard({ onPage, onNewOrder, onSelect, userName }: { onPage: (page: string) => void; onNewOrder: () => void; onSelect: (order: PedidoResponse) => void; userName?: string }) {
  const [orders, setOrders] = useState<PedidoResponse[]>([]);
  const [activeId, setActiveId] = useState("");
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<PageResponse<PedidoResponse>>("/pedidos", {}, { size: 100 }).then((page) => { setOrders(page.content); setActiveId(page.content[0]?.id ?? ""); }).catch((reason) => setError(errorMessage(reason))); }, []);
  const activeOrder = orders.find((order) => order.id === activeId);
  const totals = { process: orders.filter((order) => order.estado === "En proceso").length, approved: orders.filter((order) => order.estado === "Aprobado").length, paid: orders.filter((order) => order.estado === "Pagado").length, total: orders.reduce((sum, order) => sum + order.total, 0) };
  return <div className="page"><div className="page-heading dashboard-heading"><div><h1>Buenos días, {userName ?? ""}</h1><p>Hay {totals.process} pedidos para revisar.</p></div><button className="button primary new-order" onClick={onNewOrder}><Plus size={19} />Nuevo pedido</button></div>{error && <p className="login-pending" role="alert">{error}</p>}<div className="metrics"><Metric label="En proceso" value={String(totals.process)} tone="blue" /><Metric label="Aprobados" value={String(totals.approved)} tone="green" /><Metric label="Pagados" value={String(totals.paid)} tone="green" /><Metric label="Total presupuestado" value={money(totals.total)} tone="ink" /></div>{activeOrder ? <section className="desk-grid dashboard-dossier"><div className="panel order-queue"><div className="panel-head"><div><h2>Pedidos recientes</h2><p>Ingresos y revisiones pendientes.</p></div><button className="text-button" onClick={() => onPage("orders")}>Ver todos</button></div><div className="compact-orders">{orders.slice(0, 5).map((order) => <button className={activeId === order.id ? "selected" : ""} key={order.id} onClick={() => setActiveId(order.id)}><div><strong>{order.numero}</strong><span>{order.cliente} · {order.moto}</span></div><StatusBadge status={order.estado} /><strong>{money(order.total)}</strong></button>)}</div></div><div className="panel dossier-preview"><div className="dossier-kicker"><span>Dossier del pedido</span><StatusBadge status={activeOrder.estado} /></div><h2>{activeOrder.numero}</h2><div className="dossier-identity"><div><span>Cliente</span><strong>{activeOrder.cliente}</strong></div><div><span>Moto</span><strong>{activeOrder.moto}</strong><small>{activeOrder.patente}</small></div></div><div className="dossier-note"><span>Motivo de ingreso</span><p>{activeOrder.observaciones || "Sin observaciones."}</p></div><div className="dossier-lines"><span>Ítems a revisar</span>{activeOrder.items.map((item) => <div key={item.id}><b>{item.descripcion}</b><small>{item.tipo} · {money(item.subtotal)}</small></div>)}</div><div className="dossier-total"><span>Total estimado</span><strong>{money(activeOrder.total)}</strong></div><button className="button primary" onClick={() => onSelect(activeOrder)}><Edit3 size={17} />Abrir pedido</button></div></section> : <EmptyState title="No hay pedidos" body="Creá un pedido para comenzar a administrar el taller." action={<button className="button primary" onClick={onNewOrder}>Nuevo pedido</button>} />}</div>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <section className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>Datos actuales</small></section>; }

export function OrdersView({ onNewOrder, onSelect }: { onNewOrder: () => void; onSelect: (order: PedidoResponse) => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"Todos" | OrderStatus>("Todos"); const [documentType, setDocumentType] = useState("Todos"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [result, setResult] = useState<PageResponse<PedidoResponse> | null>(null); const [page, setPage] = useState(1); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<PageResponse<PedidoResponse>>("/pedidos", {}, { q: query, estado: status === "Todos" ? undefined : status, documento: documentType === "Todos" ? undefined : documentType, fechaDesde: dateFrom || undefined, fechaHasta: dateTo || undefined, page: page - 1, size: 20 }).then(setResult).catch((reason) => setError(errorMessage(reason))); }, [query, status, documentType, dateFrom, dateTo, page]);
  const clear = () => { setQuery(""); setStatus("Todos"); setDocumentType("Todos"); setDateFrom(""); setDateTo(""); setPage(1); };
  const params = { q: query || undefined, estado: status === "Todos" ? undefined : status, documento: documentType === "Todos" ? undefined : documentType, fechaDesde: dateFrom || undefined, fechaHasta: dateTo || undefined };
  const list = result?.content ?? [];
  return <div className="page"><div className="page-heading"><div><h1>Pedidos</h1><p>Consultá, filtrá y administrá todas las órdenes de trabajo.</p></div><button className="button primary" onClick={onNewOrder}><Plus size={19} />Nuevo pedido</button></div>{error && <p className="login-pending" role="alert">{error}</p>}<section className="panel table-panel"><div className="filter-bar"><SearchBox value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Número o cliente" /><label><Filter size={16} /><select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setPage(1); }}><option>Todos</option>{(["En proceso", "Aprobado", "Pagado", "Cancelado"] as OrderStatus[]).map((option) => <option key={option}>{option}</option>)}</select></label><label>Tipo<select value={documentType} onChange={(event) => { setDocumentType(event.target.value); setPage(1); }}><option>Todos</option><option>Presupuesto</option><option>Factura</option></select></label><input className="filter-date" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} /><input className="filter-date" type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} /><button className="button secondary" onClick={clear}>Limpiar filtros</button><button className="button secondary" onClick={() => void download("/pedidos/export.xlsx", "pedidos.xlsx", params)}><Download size={17} />Exportar Excel</button></div>{list.length ? <table><thead><tr><th>Pedido</th><th>Cliente</th><th>Moto</th><th>Fecha</th><th>Vencimiento</th><th>Estado</th><th>Total</th><th /></tr></thead><tbody>{list.map((order) => <tr key={order.id}><td><strong>{order.numero}</strong></td><td>{order.cliente}</td><td>{order.moto}<small>{order.patente}</small></td><td>{date(order.creadoEn)}</td><td>{order.vencimiento}</td><td><StatusBadge status={order.estado} /></td><td><strong>{money(order.total)}</strong></td><td><button className="row-action" onClick={() => onSelect(order)} aria-label={`Abrir ${order.numero}`}><Edit3 size={17} /></button></td></tr>)}</tbody></table> : <EmptyState title="No encontramos pedidos" body="Probá limpiar los filtros o crear un pedido nuevo." action={<button className="button primary" onClick={onNewOrder}>Nuevo pedido</button>} />}<Pagination page={page} total={result?.totalPages || 1} onPage={setPage} /></section></div>;
}

export function OrderDetail({ order: initialOrder, onBack, onConfirm, onUpdated }: { order: PedidoResponse; onBack: () => void; onConfirm: (label: string, action: () => void | Promise<void>) => void; onUpdated: (order: PedidoResponse) => void }) {
  const [order, setOrder] = useState(initialOrder); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<PedidoResponse>(`/pedidos/${initialOrder.id}`).then((next) => { setOrder(next); onUpdated(next); }).catch((reason) => setError(errorMessage(reason))); }, [initialOrder.id, onUpdated]);
  const update = async (path: string, init: RequestInit) => { const next = await api<PedidoResponse>(path, init); setOrder(next); onUpdated(next); };
  const pieces = order.items.filter((item) => item.tipo === "Pieza").reduce((sum, item) => sum + item.subtotal, 0); const jobs = order.items.filter((item) => item.tipo === "Trabajo").reduce((sum, item) => sum + item.subtotal, 0);
  return <div className="page"><button className="back" onClick={onBack}>← Volver a pedidos</button>{error && <p className="login-pending" role="alert">{error}</p>}<div className="detail-title"><div><p>{order.numero}</p><h1>{order.cliente}</h1><span>{order.moto} · {order.patente}</span></div><div><StatusBadge status={order.estado} /><strong>{money(order.total)}</strong></div></div><section className="detail-grid"><div className="form-stack"><div className="panel"><div className="panel-head"><div><h2>Detalle de reparación</h2><p>Creado el {date(order.creadoEn)} · Vence el {order.vencimiento}</p></div><button className="button secondary" onClick={() => void download(`/pedidos/${order.id}/pdf`, `${order.numero}.pdf`)}><FileDown size={17} />PDF</button></div><p className="observation">{order.observaciones || "Sin observaciones."}</p><table><thead><tr><th>Ítem</th><th>Tipo</th><th>Cant.</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td><strong>{item.descripcion}</strong></td><td>{item.tipo}</td><td>{item.cantidad}</td><td>{money(item.precioUnitario)}</td><td>{money(item.subtotal)}</td></tr>)}</tbody></table></div></div><aside className="summary"><h2>Resumen monetario</h2><div><span>Subtotal de trabajos</span><strong>{money(jobs)}</strong></div><div><span>Subtotal de piezas</span><strong>{money(pieces)}</strong></div><div><span>Descuento global</span><strong>{money(order.descuentoGlobal)}</strong></div><div className="total"><span>Total final</span><strong>{money(order.total)}</strong></div>{order.estado === "Aprobado" && <button className="button primary large" onClick={() => onConfirm("Confirmar pago", () => update(`/pedidos/${order.id}/estado`, { method: "PATCH", body: JSON.stringify({ estado: "Pagado" }) }))}>Confirmar pago</button>}{["En proceso", "Aprobado"].includes(order.estado) && <button className="button secondary" onClick={() => onConfirm("Cancelar pedido", () => update(`/pedidos/${order.id}/estado`, { method: "PATCH", body: JSON.stringify({ estado: "Cancelado" }) }))}>Cancelar pedido</button>}<button className="button secondary" onClick={() => void download("/pedidos/export.xlsx", `${order.numero}.xlsx`, { numero: order.numero })}><Download size={17} />Exportar Excel</button><button className="button secondary" onClick={() => onConfirm("Duplicar pedido", async () => { const duplicated = await api<PedidoResponse>(`/pedidos/${order.id}/duplicate`, { method: "POST" }); onUpdated(duplicated); })}>Duplicar pedido</button>{order.estado !== "Pagado" && <button className="button danger-outline" onClick={() => onConfirm("Eliminar pedido", async () => { await api(`/pedidos/${order.id}`, { method: "DELETE" }); onBack(); })}><Trash2 size={17} />Eliminar pedido</button>}</aside></section></div>;
}

export function ReportsView() {
  const [summary, setSummary] = useState<ReporteResponse[]>([]); const [evolution, setEvolution] = useState<ReporteResponse[]>([]); const [topItems, setTopItems] = useState<ReporteResponse[]>([]); const [clients, setClients] = useState<ClienteResponse[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api<ReporteResponse[]>("/reportes/resumen"), api<ReporteResponse[]>("/reportes/evolucion"), api<ReporteResponse[]>("/reportes/top-items"), api<PageResponse<ClienteResponse>>("/clientes", {}, { size: 20, sortBy: "nombre" })]).then(([nextSummary, nextEvolution, nextTopItems, clientPage]) => { setSummary(nextSummary); setEvolution(nextEvolution); setTopItems(nextTopItems); setClients(clientPage.content); }).catch((reason) => setError(errorMessage(reason))); }, []);
  const highest = Math.max(...evolution.map((item) => item.valor), 1);
  return <div className="page"><div className="page-heading"><div><h1>Reportes</h1><p>Indicadores actuales de presupuestos, pagos y actividad del taller.</p></div></div>{error && <p className="login-pending" role="alert">{error}</p>}<div className="metrics">{summary.map((item, index) => <Metric key={item.etiqueta} label={item.etiqueta} value={item.etiqueta === "Facturado" ? money(item.valor) : String(item.valor)} tone={index === 2 ? "green" : "blue"} />)}</div><section className="desk-grid report-grid"><div className="panel"><div className="panel-head"><div><h2>Evolución</h2><p>Importes acumulados por fecha.</p></div></div><div className="bar-chart">{evolution.map((item) => <div key={item.etiqueta}><i style={{ height: `${Math.max((item.valor / highest) * 180, 4)}px` }} /><span>{item.etiqueta}</span><b>{money(item.valor)}</b></div>)}</div></div><div className="panel"><h2>Más frecuentes</h2>{topItems.map((item, index) => <div className="rank" key={item.etiqueta}><b>{String(index + 1).padStart(2, "0")}</b><span>{item.etiqueta}</span><strong>{item.valor}</strong></div>)}</div></section><section className="panel report-table"><div className="panel-head"><div><h2>Clientes con más pedidos</h2><p>Datos actuales de la cartera de clientes.</p></div></div><table><thead><tr><th>Cliente</th><th>Pedidos</th><th>Motos</th></tr></thead><tbody>{clients.map((client) => <tr key={client.id}><td>{client.nombre}</td><td>{client.pedidos}</td><td>{client.motos}</td></tr>)}</tbody></table></section></div>;
}
