"use client";

import { useEffect, useState } from "react";
import { Download, FileDown, Filter, Plus } from "lucide-react";
import { api, download, objectUrl } from "../lib/api";
import { money } from "../lib/format";
import type { ClienteResponse, DashboardResponse, OrderStatus, PageResponse, PedidoResponse, PhotoResponse, ReporteResponse } from "../lib/types";
import { EmptyState, Pagination, SearchBox, StatusBadge } from "./ui";

const date = (value: string) => new Intl.DateTimeFormat("es-AR").format(new Date(value));
const errorMessage = (reason: unknown) => reason instanceof Error ? reason.message : "No fue posible cargar la información.";

function OrderPhotos({ photos }: { photos: PhotoResponse[] }) {
  const [urls, setUrls] = useState<Record<string, string>>({});
  const key = photos.map((photo) => photo.id).join(",");
  useEffect(() => { let active = true; let loaded: Record<string, string> = {}; void Promise.all(photos.map(async (photo) => [photo.id, await objectUrl(photo.url)] as const)).then((entries) => { loaded = Object.fromEntries(entries); if (active) setUrls(loaded); else Object.values(loaded).forEach(URL.revokeObjectURL); }).catch(() => undefined); return () => { active = false; Object.values(loaded).forEach(URL.revokeObjectURL); }; }, [key]);
  if (!photos.length) return null;
  return <section className="order-photos"><h3>Fotos adjuntas</h3><div>{photos.map((photo) => urls[photo.id] ? <a key={photo.id} href={urls[photo.id]} target="_blank" rel="noreferrer"><img src={urls[photo.id]} alt={photo.filename} /></a> : <span key={photo.id}>Cargando foto...</span>)}</div></section>;
}

export function Dashboard({ onPage, onNewOrder, onSelect, userName }: { onPage: (page: string) => void; onNewOrder: () => void; onSelect: (order: PedidoResponse) => void; userName?: string }) {
  const now = new Date(); const defaultFrom = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10); const defaultTo = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);
  const [from, setFrom] = useState(defaultFrom); const [to, setTo] = useState(defaultTo); const [data, setData] = useState<DashboardResponse | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<DashboardResponse>("/dashboard", {}, { fechaDesde: from, fechaHasta: to }).then(setData).catch((reason) => setError(errorMessage(reason))); }, [from, to]);
  const max = Math.max(...(data?.evolucion.map((day) => day.total) ?? []), 1);
  return <div className="page"><div className="page-heading"><div><h1>Buenos días, {userName}</h1><p>Actividad y facturación del período seleccionado.</p></div><button className="button primary" onClick={onNewOrder}><Plus size={19} />Nuevo pedido</button></div><section className="panel dashboard-filters"><label>Desde<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Hasta<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></label></section>{error && <p className="login-pending">{error}</p>}{data && <><div className="metrics"><Metric label="Pedidos" value={String(data.pedidos)} tone="blue" /><Metric label="En proceso" value={String(data.enProceso)} tone="blue" /><Metric label="Presupuestado" value={money(data.presupuestado)} tone="ink" /><Metric label="Facturado" value={money(data.facturado)} tone="green" /></div><section className="desk-grid"><div className="panel"><div className="panel-head"><div><h2>Facturación diaria</h2><p>Importe total de pedidos creados por día.</p></div></div><div className="bar-chart">{data.evolucion.length ? data.evolucion.map((day) => <div key={day.fecha}><i style={{ height: `${Math.max(day.total / max * 180, 4)}px` }} /><span>{day.fecha.slice(8)}</span><b>{money(day.total)}</b></div>) : <p>Sin pedidos en este período.</p>}</div></div><div className="panel"><div className="panel-head"><div><h2>Pedidos recientes</h2><p>Últimos movimientos del período.</p></div><button className="text-button" onClick={() => onPage("orders")}>Ver todos</button></div><div className="compact-orders">{data.recientes.map((order) => <button key={order.id} onClick={() => void api<PedidoResponse>(`/pedidos/${order.id}`).then(onSelect).catch((reason) => setError(errorMessage(reason)))}><div><strong>{order.numero}</strong><span>{order.cliente} · {order.moto}</span></div><StatusBadge status={order.estado} /><strong>{money(order.total)}</strong></button>)}</div></div></section></>}</div>;
}

export function OrdersView({ onNewOrder, onSelect }: { onNewOrder: () => void; onSelect: (order: PedidoResponse) => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"Todos" | OrderStatus>("Todos"); const [result, setResult] = useState<PageResponse<PedidoResponse> | null>(null); const [page, setPage] = useState(1); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<PageResponse<PedidoResponse>>("/pedidos", {}, { q: query || undefined, estado: status === "Todos" ? undefined : status, page: page - 1, size: 20 }).then(setResult).catch((reason) => setError(errorMessage(reason))); }, [query, status, page]);
  const params = { q: query || undefined, estado: status === "Todos" ? undefined : status };
  return <div className="page"><div className="page-heading"><div><h1>Pedidos</h1><p>Consultá y administrá las órdenes de trabajo.</p></div><button className="button primary" onClick={onNewOrder}><Plus size={19} />Nuevo pedido</button></div>{error && <p className="login-pending">{error}</p>}<section className="panel table-panel"><div className="filter-bar"><SearchBox value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Número o cliente" /><label><Filter size={16} /><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option>Todos</option>{(["En proceso", "Aprobado", "Pagado", "Cancelado"] as OrderStatus[]).map((option) => <option key={option}>{option}</option>)}</select></label><button className="button secondary" onClick={() => void download("/pedidos/export.xlsx", "pedidos.xlsx", params).catch((reason) => setError(errorMessage(reason)))}><Download size={17} />Exportar Excel</button></div>{result?.content.length ? <table><thead><tr><th>Pedido</th><th>Cliente</th><th>Moto</th><th>Estado</th><th>Total</th><th /></tr></thead><tbody>{result.content.map((order) => <tr key={order.id}><td>{order.numero}</td><td>{order.cliente}</td><td>{order.moto}<small>{order.patente}</small></td><td><StatusBadge status={order.estado} /></td><td>{money(order.total)}</td><td><button className="row-action" onClick={() => onSelect(order)}>Ver</button></td></tr>)}</tbody></table> : <EmptyState title="No hay pedidos" body="Creá uno nuevo o ajustá los filtros." />}<Pagination page={page} total={result?.totalPages || 1} onPage={setPage} /></section></div>;
}

export function OrderDetail({ order: initialOrder, onBack, onConfirm, onUpdated }: { order: PedidoResponse; onBack: () => void; onConfirm: (label: string, action: () => void | Promise<void>) => void; onUpdated: (order: PedidoResponse) => void }) {
  const [order, setOrder] = useState(initialOrder); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void api<PedidoResponse>(`/pedidos/${initialOrder.id}`).then((next) => { setOrder(next); onUpdated(next); }).catch((reason) => setError(errorMessage(reason))); }, [initialOrder.id]);
  const update = async (path: string) => { const next = await api<PedidoResponse>(path, { method: "PATCH", body: JSON.stringify({ estado: "Pagado" }) }); setOrder(next); onUpdated(next); };
  return <div className="page"><button className="back" onClick={onBack}>← Volver a pedidos</button>{error && <p className="login-pending">{error}</p>}<div className="detail-title"><div><p>{order.numero}</p><h1>{order.cliente}</h1><span>{order.moto} · {order.patente}</span></div><div><StatusBadge status={order.estado} /><strong>{money(order.total)}</strong></div></div><section className="detail-grid"><div className="form-stack"><section className="panel"><div className="panel-head"><h2>Detalle de reparación</h2><button className="button secondary" onClick={() => void download(`/pedidos/${order.id}/pdf`, `${order.numero}.pdf`).catch((reason) => setError(errorMessage(reason)))}><FileDown size={17} />PDF</button></div><p className="observation">{order.observaciones || "Sin observaciones."}</p><table><thead><tr><th>Ítem</th><th>Tipo</th><th>Cant.</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td>{item.descripcion}</td><td>{item.tipo}</td><td>{item.cantidad}</td><td>{money(item.precioUnitario)}</td><td>{money(item.subtotal)}</td></tr>)}</tbody></table><OrderPhotos photos={order.fotos} /></section></div><aside className="summary"><h2>Resumen monetario</h2><div className="total"><span>Total final</span><strong>{money(order.total)}</strong></div>{order.estado === "Aprobado" && <button className="button primary large" onClick={() => onConfirm("Confirmar pago", () => update(`/pedidos/${order.id}/estado`))}>Confirmar pago</button>}</aside></section></div>;
}

export function ReportsView() {
  const [summary, setSummary] = useState<ReporteResponse[]>([]); const [clients, setClients] = useState<ClienteResponse[]>([]);
  useEffect(() => { void Promise.all([api<ReporteResponse[]>("/reportes/resumen"), api<PageResponse<ClienteResponse>>("/clientes", {}, { size: 20 })]).then(([nextSummary, page]) => { setSummary(nextSummary); setClients(page.content); }); }, []);
  return <div className="page"><div className="page-heading"><div><h1>Reportes</h1><p>Indicadores actuales del taller.</p></div></div><div className="metrics">{summary.map((item) => <section className="metric blue" key={item.etiqueta}><span>{item.etiqueta}</span><strong>{item.etiqueta === "Facturado" ? money(item.valor) : item.valor}</strong></section>)}</div><section className="panel"><h2>Clientes</h2><table><tbody>{clients.map((client) => <tr key={client.id}><td>{client.nombre}</td><td>{client.pedidos} pedidos</td></tr>)}</tbody></table></section></div>;
}
