import type {
  AuditoriaResponse,
  ClienteResponse,
  ItemCatalogoResponse,
  MotovehiculoResponse,
  PedidoResponse,
  ReporteResponse,
} from "./types";

export const orders: PedidoResponse[] = [
  {
    id: "1",
    numero: "PT-000189",
    cliente: "Martín R. López",
    moto: "Honda CB 190R",
    patente: "A123BCD",
    creadoEn: "24/05/2026",
    vencimiento: "31/05/2026",
    estado: "En proceso",
    documento: "Presupuesto",
    clienteId: "c1",
    motovehiculoId: "m1",
    observaciones:
      "Revisión general. Falla intermitente en arranque eléctrico.",
    descuentoGlobal: 0,
    iva: false,
    total: 87400,
    fotos: [],
    items: [
      {
        id: "i1",
        descripcion: "Diagnóstico eléctrico",
        tipo: "Trabajo",
        cantidad: 1,
        precioUnitario: 18500,
        descuento: 0,
        subtotal: 18500,
      },
      {
        id: "i2",
        descripcion: "Cambio de batería",
        tipo: "Pieza",
        cantidad: 1,
        precioUnitario: 68900,
        descuento: 0,
        subtotal: 68900,
      },
    ],
  },
  {
    id: "2",
    numero: "PT-000188",
    cliente: "Lucía A. Peralta",
    moto: "Yamaha FZ 25",
    patente: "A234EFG",
    creadoEn: "24/05/2026",
    vencimiento: "30/05/2026",
    estado: "Aprobado",
    documento: "Presupuesto",
    clienteId: "c2",
    motovehiculoId: "m2",
    observaciones: "Service periódico de 10.000 km.",
    descuentoGlobal: 0,
    iva: false,
    total: 126500,
    fotos: [],
    items: [
      {
        id: "i3",
        descripcion: "Service completo",
        tipo: "Trabajo",
        cantidad: 1,
        precioUnitario: 46000,
        descuento: 0,
        subtotal: 46000,
      },
      {
        id: "i4",
        descripcion: "Kit de transmisión",
        tipo: "Pieza",
        cantidad: 1,
        precioUnitario: 80500,
        descuento: 0,
        subtotal: 80500,
      },
    ],
  },
  {
    id: "3",
    numero: "PT-000187",
    cliente: "Nicolás Gutiérrez",
    moto: "Zanella ZB 110",
    patente: "B345HIJ",
    creadoEn: "23/05/2026",
    vencimiento: "29/05/2026",
    estado: "En proceso",
    documento: "Factura",
    clienteId: "c3",
    motovehiculoId: "m3",
    observaciones: "Cambio de freno delantero y control de cubierta.",
    descuentoGlobal: 4000,
    iva: true,
    total: 94380,
    fotos: [],
    items: [
      {
        id: "i5",
        descripcion: "Cambio de pastillas de freno",
        tipo: "Pieza",
        cantidad: 1,
        precioUnitario: 18500,
        descuento: 0,
        subtotal: 18500,
      },
      {
        id: "i6",
        descripcion: "Reparación de freno delantero",
        tipo: "Trabajo",
        cantidad: 1,
        precioUnitario: 27500,
        descuento: 0,
        subtotal: 27500,
      },
    ],
  },
  {
    id: "4",
    numero: "PT-000186",
    cliente: "Diego Fernández",
    moto: "Bajaj Rouser NS 200",
    patente: "C456KLM",
    creadoEn: "23/05/2026",
    vencimiento: "28/05/2026",
    estado: "Pagado",
    documento: "Factura",
    clienteId: "c4",
    motovehiculoId: "m4",
    observaciones: "Reparación de carburador finalizada.",
    descuentoGlobal: 0,
    iva: true,
    total: 112200,
    fotos: [],
    items: [
      {
        id: "i7",
        descripcion: "Reparación de carburador",
        tipo: "Trabajo",
        cantidad: 1,
        precioUnitario: 92727,
        descuento: 0,
        subtotal: 92727,
      },
    ],
  },
  {
    id: "5",
    numero: "PT-000185",
    cliente: "Facundo Torres",
    moto: "Gilera Smash 110",
    patente: "D567NOP",
    creadoEn: "22/05/2026",
    vencimiento: "27/05/2026",
    estado: "Cancelado",
    documento: "Presupuesto",
    clienteId: "c5",
    motovehiculoId: "m5",
    observaciones: "Cliente pospone reparación.",
    descuentoGlobal: 0,
    iva: false,
    total: 35000,
    fotos: [],
    items: [
      {
        id: "i8",
        descripcion: "Cambio de cámara",
        tipo: "Pieza",
        cantidad: 1,
        precioUnitario: 12000,
        descuento: 0,
        subtotal: 12000,
      },
      {
        id: "i9",
        descripcion: "Mano de obra",
        tipo: "Trabajo",
        cantidad: 1,
        precioUnitario: 23000,
        descuento: 0,
        subtotal: 23000,
      },
    ],
  },
];

export const clients: ClienteResponse[] = [
  {
    id: "c1",
    nombre: "Martín R. López",
    telefono: "11 5555 6677",
    documento: "32.123.456",
    activo: true,
    motos: 1,
    pedidos: 4,
  },
  {
    id: "c2",
    nombre: "Lucía A. Peralta",
    telefono: "11 4234 1199",
    activo: true,
    motos: 2,
    pedidos: 3,
  },
  {
    id: "c3",
    nombre: "Nicolás Gutiérrez",
    telefono: "11 6112 9087",
    activo: true,
    motos: 1,
    pedidos: 2,
  },
  {
    id: "c4",
    nombre: "Diego Fernández",
    telefono: "11 4581 8720",
    activo: true,
    motos: 1,
    pedidos: 5,
  },
  {
    id: "c5",
    nombre: "Facundo Torres",
    telefono: "11 5591 4322",
    activo: true,
    motos: 1,
    pedidos: 1,
  },
];
export const vehicles: MotovehiculoResponse[] = [
  {
    id: "m1",
    clienteId: "c1",
    cliente: "Martín R. López",
    marca: "Honda",
    modelo: "CB 190R",
    patente: "A123BCD",
    anio: 2022,
    kilometraje: 23450,
    color: "Negro",
    cilindrada: "190 cc",
    activo: true,
  },
  {
    id: "m2",
    clienteId: "c2",
    cliente: "Lucía A. Peralta",
    marca: "Yamaha",
    modelo: "FZ 25",
    patente: "A234EFG",
    anio: 2021,
    kilometraje: 18700,
    color: "Azul",
    cilindrada: "250 cc",
    activo: true,
  },
  {
    id: "m3",
    clienteId: "c3",
    cliente: "Nicolás Gutiérrez",
    marca: "Zanella",
    modelo: "ZB 110",
    patente: "B345HIJ",
    anio: 2023,
    kilometraje: 9200,
    color: "Rojo",
    cilindrada: "110 cc",
    activo: true,
  },
  {
    id: "m4",
    clienteId: "c4",
    cliente: "Diego Fernández",
    marca: "Bajaj",
    modelo: "Rouser NS 200",
    patente: "C456KLM",
    anio: 2020,
    kilometraje: 32100,
    color: "Gris",
    cilindrada: "200 cc",
    activo: true,
  },
  {
    id: "m5",
    clienteId: "c5",
    cliente: "Facundo Torres",
    marca: "Gilera",
    modelo: "Smash 110",
    patente: "D567NOP",
    anio: 2024,
    kilometraje: 4700,
    color: "Blanco",
    cilindrada: "110 cc",
    activo: true,
  },
];
export const catalog: ItemCatalogoResponse[] = [
  "Cambio de aceite",
  "Cambio de filtro de aceite",
  "Cambio de pastillas de freno",
  "Kit de transmisión",
  "Bujía",
  "Reparación de carburador",
  "Cambio de cámara",
  "Service completo",
  "Diagnóstico eléctrico",
  "Cambio de batería",
  "Reparación de freno delantero",
].map((descripcion, index) => ({
  id: `cat${index + 1}`,
  descripcion,
  tipo:
    index === 3 || index === 4 || index === 6 || index === 9
      ? "Pieza"
      : "Trabajo",
  precioBase: [
    12500, 8500, 18500, 80500, 7500, 42000, 12000, 46000, 18500, 68900, 27500,
  ][index],
  categoria: index < 5 ? "Mecánica" : "Service",
  activo: true,
  actualizadoEn: "20/05/2026",
}));
export const audit: AuditoriaResponse[] = [
  {
    id: "a1",
    fecha: "24/05/2026 09:15",
    usuario: "Avril",
    modulo: "Pedidos",
    accion: "Edición",
    descripcion: "Actualizó el precio de Cambio de batería en PT-000189.",
  },
  {
    id: "a2",
    fecha: "23/05/2026 17:43",
    usuario: "Operario",
    modulo: "Pedidos",
    accion: "Alta",
    descripcion: "Creó PT-000189 con observación libre.",
  },
  {
    id: "a3",
    fecha: "23/05/2026 16:12",
    usuario: "Avril",
    modulo: "Catálogo",
    accion: "Precio",
    descripcion: "Actualizó el precio de Kit de transmisión.",
  },
  {
    id: "a4",
    fecha: "22/05/2026 14:31",
    usuario: "Avril",
    modulo: "Pedidos",
    accion: "Estado",
    descripcion: "Marcó PT-000186 como Pagado.",
  },
];
export const reportData: ReporteResponse[] = [
  { etiqueta: "Ene", valor: 380000 },
  { etiqueta: "Feb", valor: 425000 },
  { etiqueta: "Mar", valor: 512000 },
  { etiqueta: "Abr", valor: 468000 },
  { etiqueta: "May", valor: 615000 },
];
